"""
Django settings for Farzan project.

Generated by 'django-admin startproject' using Django 4.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

PWA_APP_DEBUG_MODE = True

PWA_APP_NAME = 'Farzan'
PWA_APP_DESCRIPTION = "ساخت توابع "
PWA_APP_THEME_COLOR = '#333'
PWA_APP_BACKGROUND_COLOR = '#000000'
PWA_APP_DISPLAY = 'standalone'
PWA_APP_SCOPE = './'
PWA_APP_ORIENTATION = 'any'
PWA_APP_START_URL = '/'
PWA_APP_STATUS_BAR_COLOR = 'default'
PWA_APP_ICONS = [
    {
   "src": "static/img/android-icon-36x36.png",
   "sizes": "36x36",
   "type": "image/png",
   "density": "0.75",
   "purpose": "any maskable"
  },
  {
   "src": "static/img/android-icon-48x48.png",
   "sizes": "48x48",
   "type": "image/png",
   "density": "1.0",
   "purpose": "any maskable"
  },
  {
   "src": "static/img/android-icon-72x72.png",
   "sizes": "72x72",
   "type": "image/png",
   "density": "1.5",
   "purpose": "any maskable"
  },
  {
   "src": "static/img/android-icon-96x96.png",
   "sizes": "96x96",
   "type": "image/png",
   "density": "2.0",
   "purpose": "any maskable"
  },
  {
    "src": "static/img/android-icon-144x144.png",
    "sizes": "144x144",
    "type": "image/png",
    "purpose": "any maskable"
  },
  {
   "src": "static/img/android-icon-192x192.png",
   "sizes": "192x192",
   "type": "image/png",
   "density": "4.0",
   "purpose": "any maskable"
  },
  {
    "src": "static/img/256x256.png",
    "sizes": "256x256",
    "type": "image/png",
    "purpose": "any maskable"
  },
  {
    "src": "static/img/1024x1024.png",
    "sizes": "1024x1024",
    "type": "image/png",
    "purpose": "any maskable"
  },
  {
    "src": "static/img/GooglePlayStore.png",
    "sizes": "512x512",
    "type": "image/png",
    "purpose": "any maskable"
  }
]
PWA_APP_ICONS_APPLE = [
   {
    "src": "static/img/apple-icon-57x57.png",
    "sizes": "57x57",
    "type": "image/png",
    "purpose": "any maskable"
  },
  {
    "src": "static/img/apple-icon-60x60.png",
    "sizes": "60x60",
    "type": "image/png",
    "purpose": "any maskable"
  },
  {
    "src": "static/img/apple-icon-72x72.png",
    "sizes": "72x72",
    "type": "image/png",
    "purpose": "any maskable"
  },
  {
    "src": "static/img/apple-icon-76x76.png",
    "sizes": "76x76",
    "type": "image/png",
    "purpose": "any maskable"
  },
  {
    "src": "static/img/apple-icon-114x114.png",
    "sizes": "114x114",
    "type": "image/png",
    "purpose": "any maskable"
  },
  {
    "src": "static/img/apple-icon-120x120.png",
    "sizes": "120x120",
    "type": "image/png",
    "purpose": "any maskable"
  },
  {
    "src": "static/img/apple-icon-144x144.png",
    "sizes": "144x144",
    "type": "image/png",
    "purpose": "any maskable"
  },
  {
    "src": "static/img/apple-icon-152x152.png",
    "sizes": "152x152",
    "type": "image/png",
    "purpose": "any maskable"
  },
  {
    "src": "static/img/apple-icon-180x180.png",
    "sizes": "180x180",
    "type": "image/png",
    "purpose": "any maskable"
  }
]

PWA_APP_DIR = 'ltr'
PWA_APP_LANG = 'en-US'

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-vfpv=r)dkor_x#=bnj$c)fuwup@nxb-pi=*lz-jwj92j-gx6yk'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'front',
    'pwa',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Farzan.urls'

STATICFILES_DIRS = (
    os.path.join(os.path.dirname(BASE_DIR), "Farzan\\front"),
)

STATIC_URL = '/static/'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# WSGI_APPLICATION = 'Farzan.wsgi.application'

PWA_SERVICE_WORKER_PATH = os.path.join(BASE_DIR, 'front\static', 'serviceworker.js')

# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/


# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'